package com.krishna.autogenerate.pojos.test;

import java.io.FileNotFoundException;
import java.io.FileReader;

import com.google.gson.Gson;
import com.google.gson.JsonIOException;
import com.google.gson.JsonSyntaxException;
import com.krishna.autogenerate.pojos.Demo;

public class TestAutoGeneratedPojos {

	public static void main(String[] args) throws JsonSyntaxException, JsonIOException, FileNotFoundException {
		String filePath = "/Users/kabothu/Documents/Workspace/AutomationWorkspace/AutoGeneratePojos/src/main/resources/schema/demo.json";

		Gson gson = new Gson();

		Demo demoObject = gson.fromJson(new FileReader(filePath), Demo.class);
		System.out.println("Latitude....." + demoObject.getDataSet().get(0).getLatitude());

	}

}
